### PR TITLE
Typo + better var name.

### PR DESCRIPTION
**Pull request by clemens-tolboom**
## Description

It to me a while what eHeadCircle was so let's make its name more explicit enemyHeadCircle
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [ ] **My code adheres to the code style of this project but most importantly of all to the things mentioned in CONTRIBUTING.md and PULL_REQUEST_TEMPLATE.md.**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ChadSki** [comment]
@clemens-tolboom I don't think I've seen you lurking in the gitter chat, but we're trying to track down why ErmiyaEskandary/master has been performing worse than j-c-m's branch.

j-c-m has been rigorously testing every change that affects the bot, only merging in changes after _hours_ of testing (usually at least ten hours) show that the average score has remained steady or improved.

We've been merging small refactor changes over the past couple days which _seem_ harmless but apparently have affected the effectiveness of the bot. Currently we're testing the past few commits to see which ones are responsible.

So... basically just an FYI that going forwards we're going to _rigorously_ test every change that affects the bot module, even if it looks harmless.

**Comment by ChadSki** [comment]
Additionally, we plan on no longer accepting PRs directly into master.

PRs should target a development branch, which is merged into master on some schedule.

We're just trying to get all this set up; might take a day or few.

**Comment by Drflash55** [comment]
You need to have things tested before they get merged...

Just merging things in, that look like they wouldn't do much, can screw up something badly.
Backups are there for a reason. @ChadSki A development branch is a wise move.

**Comment by ermiyaeskandary** [comment]
@ChadSki @Drflash55 Agreed - hence why all code will be tested in detail from now on - even the slightest change and code will be committed into dev first.

**Comment by ermiyaeskandary** [comment]
Hound not updated yet. Closing.

**Comment by clemens-tolboom** [comment]
Ehm ... not sure why this is closed. Is there an issue I can read about the new strategy?

Maybe we need a CONTRIBUTING.md explaining the whole development workflow.

I certainly can help with setting up the Gitflow wayand do propeer release cycle.

**Comment by ermiyaeskandary** [comment]
@clemens-tolboom Currently we do have a CONTRIBUTING.md and a new template but that's not the issue. You need to make a new PR targeting the dev branch and so the dog is also updated. :+1:

**Comment by ermiyaeskandary** [comment]
@clemens-tolboom please make a new PR and I'll merge right away as it isn't code change - just doc change.

**Pull request closed without merging**
