### PR TITLE
Drawing fix, use context.save and restore() to keep state.

### PR DESCRIPTION
**Pull request by j-c-m**

### CODE REVIEW

**Comment by ermiyaeskandary** [comment]
Does this fix the cyan bug ?

**Comment by j-c-m** [comment]
I can't reproduce the cyan bug, but it might.  It helps a lot with performance.  Someone with the cyan bug would have to test it.

**Comment by j-c-m** [comment]
I think it _should_ fix the cyan bug, I noticed it with the fill values spilling into the game itself from other drawings, and I think that was the cyan bug.

**Comment by ermiyaeskandary** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/158/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by ChadSki** [comment]
:+1: Approved

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/158/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by ermiyaeskandary** [comment]
@j-c-m Rebase and we can merge...

**Comment by ChadSki** [comment]
Why close the PR?

**Comment by ChadSki** [comment]
Ah, changes are integrated into [#165](https://github.com/ErmiyaEskandary/Slither.io-bot/pull/165) :+1:

**Pull request closed without merging**
