### PR TITLE
Custom oef (reduce food glow and other zoom maintain)

### PR DESCRIPTION
**Pull request by tjorim**
## Description

Create custom redraw() for foodglow, this modifies the standard one.

Remove the foodglow as suggested by @pllsner in #310 , the issue is also stated in #236 .
Since this modifies the redraw()-function, the zoom is altered as well
instead of calling an extra function on each redraw.
### Current bot (develop and master is the same):
- games 99
- median 1944
- average 4883
### After these commits:
- games 125
- median 2810
- average 5480

I have let a few bots run overnight, all scores where put in an excel-file where I did some quick statistics. I ran 4 bots: master, develop and 2x the custom_oef branch.

**_[Map1.xlsx](https://github.com/ErmiyaEskandary/Slither.io-bot/files/329543/Map1.xlsx)_** **<-- Here are the results!!!**

Both master and develop branches have the same bot code, you can see that the results differ a lot. This is just to demonstrate that 2 running bots can have totally different scores.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] **I have read CONTRIBUTING.md**
- [x] **I fully understand the [Github Flow](https://guides.github.com/introduction/flow/) and I'm merging into the develop branch , which is the default branch, and not the master branch**
- [x] **My code adheres to the code style of this project but most importantly of all to the things mentioned, which I have read, in CONTRIBUTING.md**
- [ ] **If my change requires a change to the documentation, I have updated the documentation in /docs accordingly.**
- [x] **I have included the results of the [test required](https://github.com/ErmiyaEskandary/Slither.io-bot/wiki/How-to-Test-Bot-Effectiveness).**

### CODE REVIEW

**Comment by tjorim** [comment]
:+1: I would say :smile: 

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/311/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by ChadSki** [comment]
Alright! Excited to see this change get in. I will test tonight!

**Comment by alexzeit** [comment]
1. The current zoom is not stored for the next game after respawn.
2. Suggestion: set the same one collor for all food (b=per_color_imgs[number])

I have tried to set one collor for all foods in the same way but without success, could you have a look on this:

```
var original_newfood = window.newFood;
var original_newfood_string = original_newfood.toString();
var newfood_string = original_newfood_string.replace(/per_color_imgs\[e.cv/gi, 'per_color_imgs[10');

window.newFood = new Function(newfood_string.substring(
newfood_string.indexOf('{') + 1, newfood_string.lastIndexOf('}'))); 
```

**Comment by ermiyaeskandary** [comment]
100% approved! Looks great and after (not alot of) testing, it doesn't seem to have an influence on performance - after all, it should be improving it anyway
Great job @tjorim !
Approved (edit: forgot)

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/311/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by ChadSki** [comment]
:+1:

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/311/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by alexzeit** [comment]
add this to improve runtime:

 if (window.playing && bot.isBotEnabled && window.snake !== null) {
				    window.redraw = function() {};
}

**Comment by tjorim** [comment]
It's already in the script somewhere.

Met vriendelijke groeten
Jorim Tielemans
Studentenvertegenwoordiger studentenraad
Student PXL-Tech (11502591)
1 Elektronica-ICT (groep D) - 2 (groep B)

<https://mail.google.com/mail/u/0/goog_1454446360>tielemans.jorim@gmail.com |
M +32(0)495 73 56 17 | www.jtlm.be
Kot Lokwentes | Plompaertstraat 17-17 | B-3590 Diepenbeek

Als u dit bericht per vergissing ontvangen hebt, dan is elke bekendmaking,
reproductie, vorm van
kopiëren verdeling of andere verspreiding of gebruik van deze communicatie
strikt verboden.
Gelieve in dit geval de afzender onmiddellijk te verwittigen en het bericht
te verwijderen.

2016-06-25 6:04 GMT+02:00 alexzeit <notifications@github.com>:

**Comment by tjorim** [comment]
@alexzeit That's already in the script somewhere.

**Comment by Seple** [comment]
Please add a standard "master" code

**Comment by ChadSki** [comment]
We need more approvals! @OneEyed @chancity @MattDuffin @Drflash55 @ErmiyaEskandary @Evanito @FliiFe @K00sKlust @j-c-m @clemens-tolboom

**Comment by tjbcg** [comment]
Approved :+1:

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/311/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by Evanito** [comment]
:+1: 
Looks good to me!

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/311/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by ermiyaeskandary** [comment]
Approved (forgot otherwise I had approved it long time ago ;))

**Comment by ChadSki** [comment]
Nice work @tjorim, thanks for landing this feature! :tada:

**Comment by HamishBlank** [comment]
Performance has dropped severely after this merge. Windows 10 Firefox 47 with greasemonkey

**Comment by tjbcg** [comment]
@HamishBlank Can you try with the commit right before the merge to confirm
this is the issue ?

**Comment by HamishBlank** [comment]
commit 420e562 is the commit right before, and screen goes completely blank edit: except for the background

commit 0e3a1b4 the one before 420e562 performance is back to normal without issues

**Comment by HamishBlank** [comment]
working fine in Google chrome 51.0.2704.103 tampermonkey windows 10, only a slight/very minimal difference between 0e3a1b4 and latest

**Comment by ChadSki** [comment]
Dang, I tested in Chrome and didn't catch this. :P

Opening issue #315 to track this.

**Pull request merged**
