### PR TITLE
Implemented the new food Algorithm

### PR DESCRIPTION
**Pull request by GibsonHF**

### CODE REVIEW

**Comment by ermiyaeskandary** [comment]
I'll test later - due to new updates, I would have to manually commit these changes if it works as there would be conflicts.

**Comment by ErmiyaEskandary** [comment]
What is speed dodge ?

**Comment by ermiyaeskandary** [comment]
Has conflicts. Close and fork again the latest version. Recommit and remake a PR.

**Comment by ermiyaeskandary** [comment]
P.S. we can fix conflicts but this is the easiest way...

**Comment by chancity** [comment]
uhh i actually coded all that new stuff @captian7...not sure why you're creating a pull request to add it

**Comment by ermiyaeskandary** [comment]
@chancity @dracco1993 This is a collaborative project and when code is made opensource, it is code for everyone. This project is licensed under MIT so :<br>
**_Permission is hereby granted_**, free of charge, to **_any person_** obtaining a copy of this software and associated documentation files (the "Software"), to **_deal in the Software without restriction_**, including without limitation the **_rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software_**

:+1:

**Comment by ermiyaeskandary** [comment]
@captian7 Please make a new PR with the new food algorithm implemented **paying attention to the pull request template and the CONTRIBUTING guideline**.

**Comment by chancity** [comment]
It just wasnt ready to be released is all.  I could careless who has the code

**Pull request closed without merging**
