### PR TITLE
collision detection: Change goal coords based on the snake part with …

### PR DESCRIPTION
**Pull request by kmatheussen**
…the shortest distance from yourself

### CODE REVIEW

**Comment by ermiyaeskandary** [comment]
What the point of this ?

**Comment by kmatheussen** [comment]
You want to steer away from the closest snake part, not just the last one in the list, which part that may be.

**Comment by kmatheussen** [comment]
I've also experienced a lot with steering more away from the head than from the rest of the snake bodies, but this has so far only made minor differences.

**Comment by ermiyaeskandary** [comment]
Can someone test ? I can test in about 30 min.

**Comment by kmatheussen** [comment]
> I've also experienced a lot with steering more away from the head than from the rest of the snake bodies, but this has so far only made minor differences.

The main reason this only makes a minor difference is that the snake now basically only dies if it gets trapped, either by being surrounded by many snakes, or, more commonly, being circled.

**Comment by kmatheussen** [comment]
If we find a way to avoid being circled + constantly move the snake out of the center of the universe (to avoid too many other snakes), I think the snake have potential to grow very very big. Now it usually grows to a size between 1000-2000 before being circled by someon.

**Comment by tom-n96** [comment]
It fixes issue #73. 
I tested it and it works fine. The only thing I noticed is that `var shortest_distance = 10000;` 
should probably be `var shortest_distance = Number.MAX_VALUE;`

**Comment by ermiyaeskandary** [comment]
Number.MAX_VALUE ? 
Why ?

**Comment by ermiyaeskandary** [comment]
I also tested it - works ..
Merging...

**Comment by kmatheussen** [comment]
> The only thing I noticed is that var shortest_distance = 10000; should probably be var shortest_distance = Number.MAX_VALUE;

Definitely. I was too lazy looking up how to get max value in javascript. Should have fixed it before submitting PR.

**Comment by chancity** [comment]
Adding a fix for this, it'll be similar to the way getSortedFood works

**Comment by chancity** [comment]
Meaning it will only dodge the closet snake part

**Comment by chancity** [comment]
I almost have line intersection detection working too, should fix
the zooming into other snakes

**Comment by tom-n96** [comment]
@ErmiyaEskandary 

> Number.MAX_VALUE ? 
> Why ?

The algorithm is comparing distances to find the lowest one. If the shortest distance happened to be above 10000, it wouldn't be lower than the starting value and wouldn't be recognized as the current shortest_distance. If the starting value were to be the maximum value a variable could hold, this could never be an issue.

I submitted a pull request with the fix to this.

@chancity 
How is that different than what @kmatheussen has already done? His fix seems to work perfectly.

**Pull request merged**
