### PR TITLE
Add middle click quick respawn

### PR DESCRIPTION
**Pull request by vmari**
## Description

Add middle click quick respawn
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] **I have read CONTRIBUTING.md**
- [x] **I fully understand the [Github Flow](https://guides.github.com/introduction/flow/) and I'm merging into the develop branch , which is the default branch, and not the master branch**
- [x] **My code adheres to the code style of this project but most importantly of all to the things mentioned, which I have read, in CONTRIBUTING.md**
- [x] **If my change requires a change to the documentation, I have updated the documentation in /docs accordingly.**
- [x] **I have included the results of the [test required](https://github.com/ErmiyaEskandary/Slither.io-bot/wiki/How-to-Test-Bot-Effectiveness).**

### CODE REVIEW

**Comment by ermiyaeskandary** [comment]
Personally, I don't see this as useful. Using ESC would be as fast as using the middle button as we are going to respawn right at the middle straight after each other, not in the middle of the game. 
Rejected

[Rejected with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/312/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by vmari** [comment]
I play & use the bot whit one hand. IMO this is very usefull when you loses and need a quick respawn, without put your 2nd and on the keyboard. That's the first reason to do this PR.

**Comment by tjorim** [comment]
Rejected, I don't think this is useful either.
Maybe we should make the autorespawn work when the bot is off though.

[Rejected with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/312/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by ChadSki** [comment]
> Maybe we should make the autorespawn work when the bot is off though.

I like this idea.

Closing this pull-request for now.

**Pull request closed without merging**
