### PR TITLE
Approximate square root of a number

### PR DESCRIPTION
**Pull request by kakol20**
## Description

It checks the nearest number below with real roots.
It takes away the numbers as the remainder the over double of the square root of the number below with real roots and add that to the square root of the number below with real roots. (I'm sorry if my explanation is not very good, my English isn't great). This method is much less pc extensive than the Math.sqrt() function. Will work with numbers that has roots. This method is much more accurate the bigger the number but less accurate the smaller the number (e.g. using this method for 2 it will be around 6% off the actual value)

Example, take 27
The nearest is 25
27 - 25 = 2
Square root of 25 = 5
The approximate answer = 5 + (2 / (5 \* 2)) = 5.2
The actual answer is 5.196 and 5.2 \* 5.2 is 27.04
## Motivation and Context

#2

Fixes @FliiFe 's comment about the Math.sqrt() function being computer expensive.
This method is much less pc extensive than the Math.sqrt() function and is an approximation since the actual distance is not needed
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ermiyaeskandary** [comment]
@kakol20 Has this been tested ?

**Comment by kakol20** [comment]
Have been tested to work yes

**Comment by ermiyaeskandary** [comment]
Approved - merging..

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/127/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by tjbcg** [comment]
Do we need any approximation ? 
Anyway, merged.

**Pull request merged**
