### PR TITLE
Make sure window.bodyCollisionRadiusMultiplier is converted to number when read back from local storage

### PR DESCRIPTION
**Pull request by kmatheussen**
And change step to 0.25.

### CODE REVIEW

**Comment by ermiyaeskandary** [comment]
Why are your commits like that ? It's weird..

**Comment by kmatheussen** [comment]
Sorry, I force pushed to my local branch once (I guess that's the reason).
I'll try to use a new branch instead.

On Thu, May 12, 2016 at 10:16 PM, Ermiya Eskandary <notifications@github.com

**Comment by kmatheussen** [comment]
Why did you close it? It fixes the the problem...

**Comment by ermiyaeskandary** [comment]
Sorry but we are currently refactoring code...
Your changes might get reverted soon. 
You can make PR's after wards...
Sincere Apologies..

**Comment by tjorim** [comment]
@kmatheussen Can you please join Gitter? It makes it easier to communicate with the team.
Here's the link: https://gitter.im/ErmiyaEskandary/Slither.io-bot

**Pull request closed without merging**
