### PR TITLE
Remove collision toggle. + Fix distance^2 math.

### PR DESCRIPTION
**Pull request by Salvationdk**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by j-c-m** [comment]
:-1:

**Comment by ermiyaeskandary** [comment]
Rejected - not useful and not a complete PR 

@j-c-m P.S: I can add you to the list for approvers if you want....

[Rejected with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/229/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by ermiyaeskandary** [comment]
What was I thinking ? lol probably read it wrong..

**Comment by ermiyaeskandary** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/229/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Pull request closed without merging**
