### PR TITLE
Added auto updater

### PR DESCRIPTION
**Pull request by jLynx**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jLynx** [comment]
This houndcli bot thing is annoying

**Comment by j-c-m** [comment]
Tampermonkey and Greasemonkey both already support updating, I don't think this is needed.

**Comment by jLynx** [comment]
@j-c-m Not auto updating like this though.
This automatically gets the latest without the user having to do anything. That's why we ended up doing this for our agar.io bot

**Comment by j-c-m** [comment]
image

Its fully automatic now.

**Comment by jLynx** [comment]
@j-c-m But that checks every day not every time you load the site

**Comment by j-c-m** [comment]
Yes, but this uses jQuery to inject a script into another greasemonkey script, its more unsafe than userscripts.

Lets look at alternatives if this level of updating is required.

Maybe setting GM_info.script.lastUpdated = 0 in the script will force an update?

**Comment by jLynx** [comment]
It has a sha to check, it's not unsafe at all. We had 10's of thousands
using it with the agar bot with no issues

**Comment by ermiyaeskandary** [comment]
Rejected
:-1: 
Already implemented and 90 code style violations found

[Rejected with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/144/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Pull request closed without merging**
