### PR TITLE
Maintain zoom distance.

### PR DESCRIPTION
**Pull request by j-c-m**
Maintain zoom distance. (Even when bot is disabled).

### CODE REVIEW

**Comment by ChadSki** [comment]
Hmm, this seems to work without lag on my beefy computer. I'll test my laggy computer when I get home.

How does this compare to @tjorim's solution, which [fixes the root cause](https://github.com/ErmiyaEskandary/Slither.io-bot/issues/97#issuecomment-219291847)?

**Comment by j-c-m** [comment]
It shouldn't lag at all, it resets window.gsc before the redraw() calcs take place every frame.

**Comment by tjorim** [comment]
@ErmiyaEskandary I thought no PRs would be merged for now?
This might be a good solution as well, but this adds an extra check to see if the zoomlevel has changed.

Where just removing the lines (which probably won't change) only gets executed once, this function is done each cycle. Like i see it:
1. **Our** `oef()`-function gets executed.
2. It calls the new `maintainZoom()`-function that checks if the zoomlevel has changed. If so, replace it.
3. The **original** `oef()`-function gets executed.
4. This calls the `redraw()`-function, where the zoomlevel is checked _again_ and increased/decreased if deemed necessary.
5. Everything is drawn, with a zoomlevel not equal with the desired zoomlevel (since it will still change the zoomlevel each time with steps of 2E-4). Not a big problem but it bugs me that the value still gets checked and changed (even an extra time in this new maintainZoom()-function).

**Comment by ermiyaeskandary** [comment]
@tjorim 

> I thought no PRs would be merged for now?

Major commits done - should have removed the labels I guess...

> which probably won't change

Might do - make a PR and we will compare. I'm up for reviewing different alternatives..

**Pull request merged**
