### PR TITLE
Bugfixing and new method for isBotRunning

### PR DESCRIPTION
**Pull request by Evanito**
Made on my phone so it isn't tested. Making this a pr because I don't want to merge risky code.

### CODE REVIEW

**Comment by Drflash55** [comment]
Would love to test, but I'm not at home, nor am I a Collaborator (Well, I wasn't. : | )... Plus, absolutely no knowledge about how to test codes without having it merged properly.

**Comment by Evanito** [comment]
Works fine for me.

**Comment by ermiyaeskandary** [comment]
When you toggle it off, can you move the snake ? I can't.

**Comment by Evanito** [comment]
The current code only allows arrow key control.
The code works fine for me otherwise, cleared to merge?

**Comment by ermiyaeskandary** [comment]
I think it would be best to add mouse support as well.

**Comment by Drflash55** [comment]
^^^

**Comment by ermiyaeskandary** [comment]
I'm doing it right now.

**Comment by ermiyaeskandary** [comment]
When it's done, I'll make a new commit as merging from Evanito-patch1 seems weird

**Pull request merged**
