### PR TITLE
Clearer collision check functions

### PR DESCRIPTION
**Pull request by ChadSki**
Adjust comments and temporary variables to more clearly describe what is going on.
## Description
- Explain that `quickCollisionCheck` works by pretending circles are squares.
- Rename `collisionCheck` to `slowCollisionCheck`. (Easy to rename because it is only being used by `circleIntersect`)
- Optimize `slowCollisionCheck` by moving some not-always-necessary math inside an if-statement.
- Use a `bothRadii` temporary variable, making equations easier to read and preventing redundant calculation.
## Motivation and Context

I like to clean up code in order to better understand it.
## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ChadSki** [comment]
Hmm, given that quickCollisionCheck and slowCollisionCheck are only used by circleIntersect, maybe they should just be inlined?

**Comment by ermiyaeskandary** [comment]
@chancity ~~Type of change ?~~
Merging... Great that you are commenting things.... 
_Really_ helps out other people to understand your code ...

**Comment by ermiyaeskandary** [comment]
@chancity 

> Hmm, given that quickCollisionCheck and slowCollisionCheck are only used by circleIntersect, maybe they should just be inlined?

:thought_balloon:

**Comment by chancity** [comment]
slow collision check adds no real value yet....this is what I'm currently using

```
// Checks to see if you are going to collide with anything in the collision detection radius
window.checkCollision = function(x, y, r) {
    if (!window.collisionDetection) return false;
    var width = window.getSnakeWidth();
    var xOffset = Math.cos(window.snake.ang) * r;
    var yOffset = Math.sin(window.snake.ang) * r;

    circle1 = collisionScreenToCanvas({x: window.getX()  + xOffset, y: window.getY() + yOffset, radius: r});
    window.drawCollisionPoint(circle1, true);

    if (window.collisionPoints[0] != null && snake.dead_amt === 0){
        circle2 = collisionScreenToCanvas(window.collisionPoints[0].circle)
        if (window.collisionCheck(circle1, circle2)) {
                window.changeGoalCoords();
                window.drawCollisionPoint(circle2, true);
                return true;
        }
    }
    return false;
};
// Change direction
window.changeGoalCoords = function() {
    window.goalCoordinates = window.mapToMouse(window.snake.xx + (window.snake.xx - window.collisionPoints[0].xx), window.snake.yy + (window.snake.yy - window.collisionPoints[0].yy));
    window.setAcceleration(0);
    window.setMouseCoordinates(goalCoordinates[0], goalCoordinates[1]);
};
// Quickly check if we are going to collide with anything
window.collisionCheck = function (circle1, circle2) {
    return (circle1.x + circle1.radius + circle2.radius > circle2.x &&
        circle1.x < circle2.x + circle1.radius + circle2.radius &&
        circle1.y + circle1.radius + circle2.radius > circle2.y &&
        circle1.y < circle2.y + circle1.radius + circle2.radius);
};
```

**Pull request merged**
