### PR TITLE
Feature/task execution

### PR DESCRIPTION
**Pull request by clemens-tolboom**
### Issue worked on
#275
### Branch

https://github.com/ErmiyaEskandary/Slither.io-bot/tree/feature/task-execution

## Description

As discussed in #266 but not completed yet here is my first stab.

My basic implementation uses a tasks list with priorities. I have added a few task
- CheckForFood: Trigger food scan. It has a changing priority to allow other tasks to be performed.
- MoveToXY move to the given waypoint
- AvoidCollisionEnemySnake: Avoid collision with other (enemy) snakes. It using existing code.
- ListTasks: List the current set of tasks. Has lowest priority
### Problem

Adding new behaviour is difficult as this is **hard coded**. With A\* it was still coded but easier to add new behavior. Furthermore we have a check for food triggered by a window timer which makes it harder too. It is not possible to add behaviour by another user script either.
### Solution

This branch decouples the code

```
// Main bot
go: function() {
```

by replacing the parts mentioned above into a task scheduler. This allows for prioritise / (de)activate / adding tasks so the behaviour is more dynamic and alterable from outside this project (ie console).

It adds menu entries to toggle tasks to test particular behaviour.
### Features

``` javascript
// Activate task
window.scheduler.getTask('MoveToXY').active = true;

// Set new point
window.scheduler.getTask('MoveToXY').point = {x: 21600, y: 21600};

// Prepare a new Task
var newTask = window.scheduler.newTask('dummy')

// Add new task
window.scheduler.addTask(newTask);

// Cannot add duplicate task ID
window.scheduler.addTask(window.scheduler.newTask('dummy'));

// Delete task
window.scheduler.deleteTask('dummy');

// Report on tasks
window.scheduler.getTask('ListTasks').execute();
```
#### Task list

```
window.scheduler.listTasks()

CheckForFood Active: true Priority: 397 Trigger food scan
AvoidCollisionEnemySnake Active: true Priority: 0 Avoid collision with other (enemy) snakes
_default Active: true Priority: 0 This is the default task which cannot be deactivated.
MoveToXY Active: false Priority: 300 Move to the given way point
```
### Menu

slither_io
### MoveToXY

slither_io
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] **My code adheres to the code style of this project but most importantly of all to the things mentioned in CONTRIBUTING.md and PULL_REQUEST_TEMPLATE.md.**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
## TODOs
- [x] Fix priority for MoveToXY (stop when reached; lower priority when nearing P(x,y)?
- [x] MoveToXY is now hard coded as move to center and never looses priority. It makes the bot reaching center.
- [x] ~~Add surround algorithm from A\* branch~~
- [x] ~~Add more from A\* branch~~
- [x] ~~Receive lots of feedback~~
- [x] Provide task getter function getTaskByID
- [x] Add default task
- [x] Remove ListTasks as that is no actual task
- [x] Add task.active boolean
- [x] Check task structure so far.
- [x] Add `schedule.init()` when entering game
- [x] #285 Create issue when PR lands regarding __ AvoidCollisionEnemySnake __ as mentioned in https://github.com/ErmiyaEskandary/Slither.io-bot/issues/275#issuecomment-223595741
- [x] #284 Create issue when PR lands to split collision snake and wall

### CODE REVIEW

**Comment by clemens-tolboom** [comment]
Thanks @houndci-bot :p

**Comment by ermiyaeskandary** [comment]
checkforfood checks for food and eats it. 
**There's no point for eat.**
- **eat doesn't work if checkforfood isn't enabled/on :(**

**Comment by ermiyaeskandary** [comment]
I presume for testing this - 3 options, which have to be and are present in the current master bot, **only need to be enabled:
- avoidcollisionenemysnake
- checkforfood

(eat) may be one if the bug ^^^ is addressed or simply **just remove it** .... @clemens-tolboom

**Comment by ermiyaeskandary** [comment]
@clemens-tolboom **The overlay is also messed up - the scores don't fully show up**

image

**Comment by ermiyaeskandary** [comment]
@clemens-tolboom 

> Below some results without MoveToXY which are not good I guess :-(

Solved ?

**Comment by ChadSki** [comment]
Running tests...
1. feature/task-execution (23aeb46)
2. develop (10dfdb6)

**Comment by ermiyaeskandary** [comment]
@ChadSki What options are you testing with for feature/task-execution ?

**Comment by ChadSki** [comment]
Defaults

options

**Comment by ermiyaeskandary** [comment]
@ChadSki :+1:

**Comment by ChadSki** [comment]
It's only been two hours so far, but the results are not looking so great. Current medians below:
1. feature/task-execution (23aeb46)
   - 4711 (11 games)
   - 1654 (9 games)
   - 3548 (11 games)
   - 1601 (16 games)
2. develop (10dfdb6)
   - 6410 (14 games)
   - 4877 (13 games)
   - 4727 (9 games)
   - 9815 (6 games)

I'll keep the test running overnight, though.

**Comment by clemens-tolboom** [comment]
@ErmiyaEskandary the task menu items are
- a feature creep seems handy
- shows all tasks needed to have the bot working.

I'm not sure the menu is that useful.

Tasks
- AvoidCollisionEnemySnake
- Eat is like grazing around current position as the bot scans for nearby food
- CheckForFood (a scheduled action every 1000/ bot.opt.targetFps \* bot.opt.foodFrames milliseconds) finding the **best new** position

Regarding the menu / score clutter. I've created #296 for that but need this first in.

@ChadSki do you have any idea what I could have missed? My guess is the speed setting to High.

I first fix the @houndci-bot remarks and hope I find the performance bug.

**Comment by ChadSki** [comment]
> Do you have any idea what I could have missed? My guess is the speed setting to High.

Probably something to do with the priority of collision avoidance vs eating food? The scores are _close-ish_ at least.

Your scheduler thing is a cool idea... I'll have to look at the code more in-depth at some point. Perhaps it's slightly negative right now because you didn't really add anything that improves the bot -- just rearranges some stuff.

If you add some behavior that makes the bot work better, that might be enough to push it ahead of develop.

**Comment by ChadSki** [comment]
20 hours of testing, here are the medians:
1. feature/task-execution (23aeb46)
   - 3669 (145 games)
   - 3969 (134 games)
   - 5347 (140 games)
   - 4171 (147 games)
2. develop (10dfdb6)
   - 6141 (122 games)
   - 3398 (148 games)
   - 4657 (132 games)
   - 6626 (115 games)

**Comment by ermiyaeskandary** [comment]
@clemens-tolboom Great! So now we should test again as we have now merged them.

**Comment by clemens-tolboom** [comment]
I've reintroduced the Eat task and added 'HuntForPrey (experimental)'.
- Eat seems necessary to trigger acceleration
- HuntForPrey needs an better algorithm thus _experimental_

I'm done with this PR and it needs a thorough code review as I cannot spend more time on it apart from code review feedback/bug reports on it. I'm out of ideas for it's performance problems. So **please help**

**Comment by ermiyaeskandary** [comment]
> Eat seems necessary to trigger acceleration

Why would it if in the current code they are together ?

**Comment by clemens-tolboom** [comment]
**CheckForFood** is triggered every `bot.opt.foodFrames`
**Eat** should run every frame if prioritised.

**Comment by clemens-tolboom** [comment]
My latest test results
slither_io_and_slither_io_and_monitoren_-_vraag___aanbod_-_tweakers

Not bad against develop.

Guess I nailed it finally with 1c35046

So needs testing by others

**Comment by ChadSki** [comment]
Median of 26? Wat? My medians are usually 3000 or so.

At least they are close to each other, haha. Can't wait to test this! (PC is still temporarily offline for repairs but will resurrect soon)

**Comment by clemens-tolboom** [comment]
Yeah ... I don't get that median ... but my laptop got screen locked ...  the scores for right side are

[14878, 10403, 7696, 2767, 472, 295, 295, 165, 164, 128, 126, 93, 54, 52, 52, 52, 51, 49, 49, 39, 39, 34, 32, 32, 29, 29, 28, 27, 27, 27, 24, 22, 20, 20, 19, 17, 17, 17, 16, 15, 15, 13, 13, 13, 11, 10, 10]

left gives `window.bot.scores`
VM492:1 Uncaught TypeError: Cannot read property 'scores' of undefined(…)

(I'm still puzzling with this window.bot === undefined now and then)

**Comment by ChadSki** [comment]
Re-reading the problem statement...

> Adding new behaviour is difficult as this is hard coded. With A\* it was still coded but easier to add new behavior. Furthermore we have a check for food triggered by a window timer which makes it harder too. It is not possible to add behaviour by another user script either.

Is this really a problem? Javascript isn't compiled, so "hard coded" isn't really a problem like it can be in other languages.

If the objective is to make the code simpler and easier to understand, then we'd need to weigh whether this change is worth adding 350+ lines. It might be more "cost-effective" to add explanatory comments.

Edit: The dynamic priority is kinda cool.

**Comment by clemens-tolboom** [comment]
@ChadSki the loop is hard coded. Enable / disable behaviour is hard. Say one wants to experiment with attack behaviour current code makes this hard.

To make this bot more intelligent we either need A\* back in or this scheduler or ... it boils down to more lines of code :-(

Having this scheduler I can write my own user script to **add** task not defined yet by us the developers with a clean interface. That's a great win too. And for my Command & Control user script / websocket app a must have being able to add new tasks like FollowTheLeader or AttachBigSnake

**Comment by ChadSki** [comment]
This pull request has been open for over a month. I think it's best if development happens on the separate branch until it is truly ready for integration.

**Comment by clemens-tolboom** [comment]
You made me very nervous closing this PR so I pushed my code to git@github.com:clemens-tolboom/Slither.io-bot.git

Note the issue summary has a separate branch https://github.com/ErmiyaEskandary/Slither.io-bot/tree/feature/task-execution but only I am working on it which s**ks

Guess this is goodbye

**Comment by ChadSki** [comment]
Nervous? The code doesn't go away, if that's what you meant -- the `feature/task-execution` branch has all your changes intact.

I like to follow your progress but pull requests are really about "I'm ready to merge, can anyone review my changes?" Since this branch isn't ready to be pulled/integrated, it shouldn't be a PR yet.

It's very easy to open a PR so I would recommend doing so once everything is ready for review.

**Pull request closed without merging**
