### PR TITLE
added stupid collision checking and requestAnimationFrame for window.loop

### PR DESCRIPTION
**Pull request by chancity**
I'm currently trying to implement the A \* star algorithm, http://www.briangrinstead.com/blog/astar-search-algorithm-in-javascript.  Change the radius values below to make the bot change its course sooner.

```
line 345: var circle1 = collisionScreenToCanvas({x: window.getX(), y: window.getY(), radius: window.getRadius()*4});

line 354:   circle2 = {x: window.snakes[snake].xx +  window.snakes[snake].fx, y: window.snakes[snake].yy +  window.snakes[snake].fy, radius: 18*window.snakes[snake].sc};

line 361:                   circle2 = {x: window.snakes[snake].pts[y].xx +  window.snakes[snake].fx, y: window.snakes[snake].pts[y].yy +  window.snakes[snake].fy, radius: 18*window.snakes[snake].sc};
```

### CODE REVIEW

**Comment by tjbcg** [comment]
Why do you try to implement the A\* algorithm ? Isn't it a pathfinding algorithm ?

**Comment by ermiyaeskandary** [comment]
> Why do you try to implement the A\* algorithm ? Isn't it a pathfinding algorithm ?

plus
We are going to do collision detection / enemy avoidance using angles. Being worked on by @FliiFe and me.

**Comment by chancity** [comment]
@FliiFe yes it is a path finding algorithm.   Convert the screen canvas into a graph/grid whatever it is.   Update the blocked cells when a snake moves and take its movement speed into account.  When a new coordinate is passed the snake will move to that location using the algorithm.

**Comment by tjbcg** [comment]
@chancity This is counter-productive. I can't even imagine the cpu expensiveness to convert to a grid, and we don't need to find any path to any specific object, just don't target objects behind snakes.

**Comment by chancity** [comment]
@ErmiyaEskandary

This is collision detection / enemy avoidance.  I'm not sure what you mean by using angles.

**Comment by chancity** [comment]
@FliiFe creating the grid only occurs once..  Updating the grids blocked cells would be as CPU expensive as checking if an object is behind a snake.  At least I think

**Comment by tjbcg** [comment]
> we don't need to find any path to any specific object, just don't target objects behind snakes.

What I meant is that the A\* algorithm is not needed for this project.

**Comment by chancity** [comment]
@FliiFe I agree its probably overkill but it intrigued me.  
http://gamedev.stackexchange.com/questions/63793/do-i-need-path-finding-to-make-ai-avoid-obstacles

https://www.dropbox.com/s/ct4v6dgmdyjshgz/asd.avi?dl=0

@ErmiyaEskandary could you explain on your vision for collision detection / enemy avoidance?

**Comment by ermiyaeskandary** [comment]
@chancity My and @FliiFe vision is that we are going to use angles to avoid enemies. Pity you can't join our Slack team at the moment otherwise you would have understood me. If we go in an enemies "danger angle" we avoid it, in simple terms.

**Comment by ermiyaeskandary** [comment]
@chancity ??
https://www.dropbox.com/s/ct4v6dgmdyjshgz/asd.avi?dl=0

**Comment by ermiyaeskandary** [comment]
enemy avoidance or killing enemies ?

**Comment by chancity** [comment]
Just a video of my current collision detection implementation

**Comment by ermiyaeskandary** [comment]
Ah ok - no lags ? What about CPU usage ?

**Comment by ermiyaeskandary** [comment]
Can others test ? Currently trying to resolve issues on my computer :(

**Comment by chancity** [comment]
The code for it is in the pull request, no lag at all.  The requestframe on
the window.loop fixed it

**Comment by ermiyaeskandary** [comment]
So according to @chancity there **should** be no lag. 

> I can't even imagine the cpu expensiveness to convert to a grid
> @FliiFe

**Comment by ermiyaeskandary** [comment]
I can't test right now - can somebody test for lag ?
FPS before and after ?

**Comment by chancity** [comment]
This isn't the A\* path finding algorithm.. It just checks for circle collisions.  It pretty much puts a big ass circle on your snakes face and s collision is detected when it collides with snake.pts[x](another circle)

**Comment by ermiyaeskandary** [comment]
?

> snake.ptsx

**Comment by chancity** [comment]
Snake.pts is an array of objects it contains the position of the snake current and past.  Past position are where dying = true

**Comment by ermiyaeskandary** [comment]
So this is temporary snake collision prevention ? Does it only avoid the head ?

**Comment by chancity** [comment]
Avoids heads Andy bodies

**Comment by ermiyaeskandary** [comment]
I can test soon. If it works, I'll tell you so you can make a new PR as this has conflicts.

**Comment by chancity** [comment]
Okay and it works,  my snakes can usually get to 2k length before it messing up.  So it doesn't work as well as I want it too.   That's why I started researching pathing algorithms.  I'm going to mess with ray collision detections too

**Comment by chancity** [comment]
The highest it's gotten is 8kish, it's fun watching it juke around.  There are certain circumstances where it has issues I.e. Snakes on each side of you

**Comment by ermiyaeskandary** [comment]
OK. We are working on #22 for this but we can use this as a temporary solution.
What do @FliiFe @Evanito @dracco1993 @Drflash55 @K00sKlust think about this as a temp solution?

**Comment by dracco1993** [comment]
If it's working as described, and not causing other trouble (FPS drop, etc.) then I'd say it's a start.

I've not looked at the code yet, so that's something I'd like to do eventually, but yeah.  👍

**Comment by ermiyaeskandary** [comment]
@chancity Close this PR and make a new one with all the latest updates so fork the latest version. Delete your current one and then fork it again. A PR with the enemy avoidance not the path finding one

**Comment by tjbcg** [comment]
@ErmiyaEskandary Can be temporary, but definitely can't be definitive.

**Comment by ermiyaeskandary** [comment]
@FliiFe Totally agreed

**Comment by chancity** [comment]
Is there any others ways you guys could communicate beside slack?

**Comment by dracco1993** [comment]
If @chancity is not familiar rebasing and such, I can probably get a clean PR in for this tonight.

**Comment by ermiyaeskandary** [comment]
@chancity Delete your current forked repo. Fork it again. Commit your changes. Make a new PR

**Comment by ermiyaeskandary** [comment]
@chancity We used to communicate using Gitter but Slack is _way_ better

**Comment by ermiyaeskandary** [comment]
@dracco1993 We'll wait a bit more :)

**Comment by ermiyaeskandary** [comment]
We won't implement angles anymore. #22
Current collision detection will be improved.

**Pull request closed without merging**
