### PR TITLE
Close enemies

### PR DESCRIPTION
**Pull request by K00sKlust**

### CODE REVIEW

**Comment by tjbcg** [comment]
Waiting for the community advice on this. Can potentially help a lot. @ErmiyaEskandary @Evanito @Drflash55 ?

**Comment by Drflash55** [comment]
Oh, sorry, didn't go on my computer when I was at home... Welp, expect me to be useless for testing until 2:50 PM EST, @FliiFe.

**Comment by Evanito** [comment]
Looks good from where I'm sitting, but I do see some missing "window."s in the bottom loop.
Once those get fixed I would pass it.

**Comment by tjbcg** [comment]
I'll merge this along with #8 
We'll revert if needed

**Comment by tjbcg** [comment]
Not going to merge #8, based on an older version.

**Comment by K00sKlust** [comment]
Strange.. I was pretty sure I had the latest version..

**Comment by tjbcg** [comment]
@K00sKlust You had, but it looks like you reverted your commits, added `window`, and then committed. That creates merge issues with git. We will add `window` in the next commit.

**Pull request merged**
