### PR TITLE
Food clustering

### PR DESCRIPTION
**Pull request by chancity**
## Description

A food method that follows the old way we had previous been getting the current food.  This uses the same math as the current computeFoodGoals.  It also flags a cluster as a cluster so that the cluster doesn't get calculated multiple times, so its less laggy.
## Motivation and Context

LAG!

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ermiyaeskandary** [comment]
Can you show proof of the face that there is higher FPS ? What does this do in general

**Comment by chancity** [comment]
The main difference is that it won't calculate a cluster twice because a
property clustered is added to the food object and the food its clustered
with.   If clustered is true skip that food.

**Comment by ermiyaeskandary** [comment]
:+1: @Drflash55 ?

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/114/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by Seple** [comment]
this optimization "food clustering" ?

**Comment by chancity** [comment]
@Seple yes

**Comment by Seple** [comment]
works properly ?

**Comment by chancity** [comment]
@Seple try it

**Comment by ermiyaeskandary** [comment]
@chancity 

> This branch has conflicts that must be resolved

**Comment by chancity** [comment]
Resolved?

**Comment by ermiyaeskandary** [comment]
We need someone else to test and approve.

**Comment by Seple** [comment]
66ecb59 On my computer it seems to work faster and fast make decisions.
but check on your own hand...

**Comment by ErmiyaEskandary** [comment]
Approved

**Comment by ksofiyuk** [comment]
Algorithmic asymptotic behavior of your algorithm is O(n^2), where n - numer of foods. 

My algorithm has the same asymptotic behavior, but it view only first 300 near points (firstly it sort them by distance), and it skip every second point. Therefore,  the number of operations  never exceeds 300 \* 300 / 2.

FPS drops to 5-10 with your algorithm , when the big snake is dead (a very large number of food points). With the algorithm, which I proposed FPS never drops below 25.

> The main difference is that it won't calculate a cluster twice because a
> property clustered is added to the food object and the food its clustered
> with.   If clustered is true skip that food.

This trick does not change the asymptotic complexity of the algorithm. 
Its algorithmic complexity is about O(n^2/K), where K ~ 5 (based on the density distribution of food points in Slither).  This improvement is doubtful, because Javascript is very slow and working with additional fields can lead to greater performance drop. 

Anyway you can implement this trick by adding a couple of lines to previous code. Why was it necessary to rewrite function from scratch?

**Comment by Seple** [comment]
@ksofiyuk Please improved versions from "use speed to go to larger clusters" Your algorithm because often accelerating and burning points;)

**Comment by chancity** [comment]
I did performance test for both solutions.  With this one a cluster is
never calculated twice.  Look at the clustered Boolean.

**Comment by ksofiyuk** [comment]
> I did performance test for both solutions.  With this one a cluster is
> never calculated twice.  Look at the clustered Boolean.

You can implement this trick by adding a couple of lines to previous code. Why was it necessary to rewrite function from scratch?

**Comment by chancity** [comment]
The distance of the food still gets updated but the clusterScore does not.

**Comment by Seple** [comment]
No problem, enjoy interest. Please new code then we compare and check ;)

**Comment by chancity** [comment]
I think we had both made a PR around the same time frame for food
clustering.

**Comment by Seple** [comment]
but the code @ksofiyuk was really a breakthrough, truth? Yes. 
Healthy competition is good for All

**Comment by ksofiyuk** [comment]
This algorithm view every point. If the number of points is large FPS drops very much.

**Comment by Seple** [comment]
again very please improved versions :+1:

**Comment by ksofiyuk** [comment]
Perhaps my algorithm in some places is slower but it always guarantees constant performance (300 \* 300 / 2 operations)

**Comment by chancity** [comment]
They both did the same (calculated a score around food based off distance) thing differently.  He came up with the center of the cluster calculation, which works awesome.

**Comment by chancity** [comment]
im going to make one that only calculates food in x sectors around snakes current location. (Going to make it generic so it works with whatever object we are interested in extrapolating)

**Comment by ksofiyuk** [comment]
Your algorithm can not provide a constant complexity. I think it very important, because 
unexpected lag can lead to bot death.

> im going to make one that only calculates food in x sectors around snakes current location. (Going to make it generic so it works with whatever object we are interested in extrapolating)

It will be good

**Comment by Seple** [comment]
"FPS drops to 5-10 with your algorithm , when the big snake is dead" - I acknowledge but it is bearable

**Comment by chancity** [comment]
The only thing that cause frame loss now is getCollisionPoints.  I'm hoping the sector thing will resolve this

**Comment by ksofiyuk** [comment]
> Please improved versions from "use speed to go to larger clusters" Your algorithm because often accelerating and burning points;)

This is easily controlled by changing only two parameters in my algorithm: cluster size threshold and cluster radius.

**Comment by Seple** [comment]
@ksofiyuk can you help me in this topic #94 ?

**Comment by Seple** [comment]
@ksofiyuk 

> Please improved versions from "use speed to go to larger clusters" Your algorithm because often accelerating and burning points;)

I do not know how to program in Java :(

**Comment by ksofiyuk** [comment]
> I do not know how to program in Java :(

```
        var sortedFood = bot.getSortedFood();
        var bestClusterIndx = 0;
        var bestClusterScore = 0;
        var bestClusterAbsScore = 0;
        var bestClusterX = 0;
        var bestClusterY = 0;

        // there is no need to view more points (for performance)
        var nIter = Math.min(sortedFood.length, 300);
        for (var i = 0; i < nIter; i += 2) {
            var clusterScore = 0;
            var clusterSize = 0;
            var clusterAbsScore = 0;
            var clusterSumX = 0;
            var clusterSumY = 0;

            var p1 = sortedFood[i];
            for (var j = 0; j < nIter; ++j) {
                var p2 = sortedFood[j];
                var dist = canvas.getDistance(p1.xx, p1.yy, p2.xx, p2.yy);
                if (dist < 100) {
                    clusterScore += p2.sz;
                    clusterSumX += p2.xx * p2.sz;
                    clusterSumY += p2.yy * p2.sz;
                    clusterSize += 1;
                }
            }
            clusterAbsScore = clusterScore;
            clusterScore /= Math.pow(p1.distance, 1.5);
            if (clusterSize > 2 && clusterScore > bestClusterScore) {
                bestClusterScore = clusterScore;
                bestClusterAbsScore = clusterAbsScore;
                bestClusterX = clusterSumX / clusterAbsScore;
                bestClusterY = clusterSumY / clusterAbsScore;
                bestClusterIndx = i;
            }
        }

        window.currentFoodX = bestClusterX;
        window.currentFoodY = bestClusterY;

        // if see a large cluster then use acceleration
        if (bestClusterAbsScore > 50) {
            window.foodAcceleration = 1;
        } else {
            window.foodAcceleration = 0;
        }
```

Change constants in lines:
`if (bestClusterAbsScore > 50) {`  -- cluster size threshold for acceleration
and 
`if (dist < 100) {` - cluster radius

**Comment by Seple** [comment]
check and test thanks ;)

**Comment by ksofiyuk** [comment]
> @ksofiyuk can you help me in this topic #94 ?

I don't understand what you want. Please explain in detail.

**Comment by Seple** [comment]
If there is a massive pile of food, the bot should temporarily decrease its collision radius to the bare minimum needed to not crash, rather than a larger fearful radius. 
`var speedingMultiplier = (window.snake.sp > 10) ? 0.8 : 1.0;`

**Comment by ksofiyuk** [comment]
> If there is a massive pile of food, the bot should temporarily decrease its collision radius to the bare minimum needed to not crash, rather than a larger fearful radius. 

After line `var speedingMultiplier = (window.snake.sp > 10) ? 1.5 : 1.0;` add following code:

```
if (typeof window.currentFood  != 'undefined' && window.currentFood.clusterScore >= 70) {
    speedingMultiplier = 0.8;
}
```

**Comment by ksofiyuk** [comment]
```
I did performance test for both solutions.  With this one a cluster is
never calculated twice.  Look at the clustered Boolean.
```

@chancity 
I test now two approaches, but your algorithm is very laggy when foods.length > 400.

**Comment by Seple** [comment]
one slightly lagy a second slightly slow - compromise?

**Comment by ksofiyuk** [comment]
> one slightly lagy a second slow - compromise

This algorithm improves nothing, but it adds this lag. 
If you change nIter from 300 to 200 in my algorithm it will be faster without losing the quality of work.

What has improved this algorithm?

**Comment by Seple** [comment]
Yeah :+1: How it will be faster react and no lagy. I prefer yours code!

**Comment by ksofiyuk** [comment]
> With this one a cluster is never calculated twice.  Look at the clustered Boolean.

Why complicate the code if previous algrorithm never lag?  Performance degradation was only due to the collision detector earlier.

**Comment by Seple** [comment]
Please create topic and deweloper: "Pull requests" ;)

**Comment by ermiyaeskandary** [comment]
Can contributors here sign the CLA linked in the readme ?

**Pull request merged**
