### PR TITLE
Previous fixes for #92 and #123

### PR DESCRIPTION
**Pull request by tjorim**
## Description

This pull request is a redo of #149 

When executing the stopBot()-function, setAcceleration back to 0.
The toggleMobileRendering()-function was not called correctly, now it does.
## Motivation and Context

When turning off the bot while it was boosting, the acceleration wasn't disabled; fixes issue #90.
This PR fixes bug #119; to maintain uniformity, some lines of code were moved as well.
The console logging setting wasn't always respected, now only the console logging is always logged.
## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ChadSki** [comment]
The remaining 7 eslint violations seem to be false-positives. Google results say that indentation problems further up in the file can confuse the linter.

I would sign off but I haven't tested the code yet. Looks good otherwise; I plan to sign off later today.

**Comment by ermiyaeskandary** [comment]
Approved..

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/157/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by ChadSki** [comment]
:+1: Approved

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/157/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by ermiyaeskandary** [comment]
@tjorim Rebase please and we'll merge

**Pull request merged**
