### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jLynx**
## Description

Updates the README.MD to include a link to interactive install website.
## Motivation and Context

It adds an interactive tutorial for those who don't want to go through the trouble of adding it manually...
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Drflash55** [comment]
:shipit: I approve of this... We could use an interactive tutorial for those who don't want to go through the trouble of adding it manually.

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/133/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/133/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by jLynx** [comment]
Also on a side note, I have made a video for those who really get stuck https://www.youtube.com/watch?v=d7mkAgQNuCA
Feel free to add this aswell if you want

**Comment by Drflash55** [comment]
@DarkN3ss61 You can add that as part of your PR, or you can notify @ErmiyaEskandary to add it in the README...

**Comment by Evanito** [comment]
:+1: 

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/133/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Pull request merged**
