### PR TITLE
Add updateURL and bot.meta.js

### PR DESCRIPTION
**Pull request by Cardridge**
This adds a file to track versioning independent from the original script.
## Description

To avoid having to re-download the entire script each time the userscript engine is checking for updates you can provide the value `@updateURL` which points to a file containing the usual userscript metadata.
## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ermiyaeskandary** [comment]
Huh ? I don't understand...

**Comment by Cardridge** [comment]
Not sure if i can explain the change better than i did in the description already.

When checking for updates Greasemonkey will need to download the entire script to compare the version numbers (45.6 KB).
With this change Greasemonkey will only need to download the header/meta file to do the same (528 Bytes).
This is both faster for the user and less traffic for github.

**Comment by ermiyaeskandary** [comment]
Understood. Needs approvals...

**Comment by Evanito** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/154/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by ermiyaeskandary** [comment]
Approved - one more and it's merged :+1: 

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/154/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Pull request merged**
