### PR TITLE
Add link to readthedoc more explicit.

### PR DESCRIPTION
**Pull request by clemens-tolboom**
## Description

I did not find the link do the documentation.
## Motivation and Context

I just learn there is an Icon to read the docs so was tempted to remove this PR but lets document this too in the contribution section.

This changes the README.md so nothing to check regarding the documentation
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [ ] **My code adheres to the code style of this project but most importantly of all to the things mentioned in CONTRIBUTING.md and PULL_REQUEST_TEMPLATE.md.**
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ermiyaeskandary** [comment]
> direcectory

**Comment by ermiyaeskandary** [comment]
Changed the badges - change the PR please. Can you also move the badge down to the documentation section you have made and update the TOC ? :+1:

**Comment by clemens-tolboom** [comment]
Not sure I changed the badge correctly.

**Comment by clemens-tolboom** [comment]
You can squash this PR :-)

**Comment by ermiyaeskandary** [comment]
Can you remove your fork and fork it again? Yours isn't fully updated yet...

**Comment by ermiyaeskandary** [comment]
It still has the Join Gitter sections...

**Comment by clemens-tolboom** [comment]
Doh ... in https://github.com/ErmiyaEskandary/Slither.io-bot/pull/267#issuecomment-222722170 you meant " I changed the ... " while I read it as a request for me to do :p

**Comment by ermiyaeskandary** [comment]
lol I can make the changes if you like - just add the section, move the badge, update the TOC and make a PR :+1:

**Comment by clemens-tolboom** [comment]
New PR is there. Thanks for the quick responses. Hope I can contrib to the bot soon ;-)

**Comment by ermiyaeskandary** [comment]
Invitation for becoming a collaborator sent :+1:

**Pull request closed without merging**
