### PR TITLE
Bot testing food clusters settimeout

### PR DESCRIPTION
**Pull request by chancity**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ermiyaeskandary** [comment]
Why did you remove high score ?

**Comment by chancity** [comment]
because people were complaining it was covering the menu and it's useless.

**Comment by ermiyaeskandary** [comment]
Please resolve hounds comments ...

**Comment by ermiyaeskandary** [comment]
Who's was complaining ? Where was the high score located ? I haven't even noticed it :(

**Comment by chancity** [comment]
hound — No violations found. Woof!

**Comment by ChadSki** [comment]
@chancity a casual check of your diff shows lots of tab characters... I'm not sure why Hound says it's satisfied but there is still stuff to clean up.

I'm also disappointed to see the high score go away.. :confused:

**Comment by ermiyaeskandary** [comment]
@chancity Please configure your text editor to use 4 spaces for tab or jsut don't use tab. Your code has a lot of code style errors - please resolve. 

P.S : don't know why Hound is saying no violations found..

**Comment by ermiyaeskandary** [comment]
@chancity Status ? Fixing it or not ?

**Pull request closed without merging**
