### PR TITLE
Fixed Overlay

### PR DESCRIPTION
**Pull request by Salvationdk**
## Description

Moved status div box down to avoid the overlay starting in the menu box.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] **I have read CONTRIBUTING.md**
- [x] **I fully understand the [Github Flow](https://guides.github.com/introduction/flow/) and I'm merging into the develop branch , which is the default branch, and not the master branch**
- [x] **My code adheres to the code style of this project but most importantly of all to the things mentioned, which I have read, in CONTRIBUTING.md**
- [ ] **If my change requires a change to the documentation, I have updated the documentation in /docs accordingly.**
- [ ] **I have included the results of the [test required](https://github.com/ErmiyaEskandary/Slither.io-bot/wiki/How-to-Test-Bot-Effectiveness).**

statusOerlay DIV moved down to avoid overlap with menu

### CODE REVIEW

**Comment by ermiyaeskandary** [comment]
Why? What's wrong with the current overlay ?

**Comment by Salvationdk** [comment]
it overlaps the menu on scores data

**Comment by Salvationdk** [comment]
nofix-fix

**Comment by ermiyaeskandary** [comment]
@Salvationdk It doesn't for me and I've just reinstalled it from the develop branch :confused: 
image

**Comment by Salvationdk** [comment]
font is different than mine...

**Comment by Salvationdk** [comment]
http://stackoverflow.com/questions/10450091/consolas-smaller-than-verdana

**Comment by ChadSki** [comment]
We should fix this once and for all by using some sort of stackpanel instead of absolute coordinates.

**Comment by ermiyaeskandary** [comment]
Confirmed by changing fonts.
I'll go with the benefit of the doubt and be cautious so I'm merging with develop...
:+1: 

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/295/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Pull request merged**
