### PR TITLE
Added getCollisionPoints, removed sortPrey and sortFood, added sortDi…

### PR DESCRIPTION
**Pull request by chancity**
## Description

Added a method called bot.getCollisionPoints.  This method gets all of the collsion points (pts) and sorts them by distance.  It is used in the new checkCollsion.  Doing this allows us to use the collision points in the future.  sortPrey and sortFood where doing the same thing so sortDistance was created.
## Motivation and Context

Clean up and future use of collision points.  Removed unused method requestAnimationFrame.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

…stance

### CODE REVIEW

**Comment by Drflash55** [comment]
Not able to test this... School will no longer allow me to play Slither.io

At 3:50 PM I might be good... @ErmiyaEskandary, or @ChadSki can you test this out?

EDIT: @chancity Please update your branch again, it's outdated.

**Comment by chancity** [comment]
@Drflash55 done

**Comment by ermiyaeskandary** [comment]
Can someone test ?

**Comment by Seple** [comment]
Does not respond to a dead snake
It does not work "Speed ​​food" dead snake

**Comment by ermiyaeskandary** [comment]
??

**Comment by Seple** [comment]
Please add - Eat fast (food) a dead snake - high priority

**Comment by chancity** [comment]
@ErmiyaEskandary @Seple 

he was right. the sort method in getSortedFood was incorrect.  Should be fixed now, try it.

**Comment by Seple** [comment]
Please correct the acceleration (towards / road) = quickly eat a dead snake

**Comment by chancity** [comment]
It should be there already

**Comment by Seple** [comment]
does not accelerate ROAD --->>> dead snake

**Comment by chancity** [comment]
it accelerates if the cluster size is big enough

**Comment by Seple** [comment]
Yes  my mistake sorry. 
...but could be better?

**Comment by Seple** [comment]
Yeah! Good job thanks :D

**Pull request merged**
