### PR TITLE
Move swaths of code into modules

### PR DESCRIPTION
**Pull request by ChadSki**
Create `canvas`, `bot`, and `userInterface` modules and move functions inside.

Following the module pattern described [here](https://toddmotto.com/mastering-the-module-pattern/).
## Description

No functional changes. Only reorganizing code and adjusting comments.
## Motivation and Context

Keeps code organized by intent, following [issue #82](https://github.com/ErmiyaEskandary/Slither.io-bot/issues/82)
## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ChadSki** [comment]
Not sure whether my change requires a change to the documentation. Methods are now inside modules, so for example you now do `graphics.drawLine(...);` instead of `window.drawLine(...);`.

**Comment by ChadSki** [comment]
Btw it is easier to view the [whole thing](https://github.com/ChadSki/Slither.io-bot/blob/organize-code/bot.user.js) than to look at the diff. The diff is messy because indentation was changed almost everywhere.

**Comment by ermiyaeskandary** [comment]
Great - keep the good work up ! This would increase the code's readability. Please post further updates here as well with clear commit names and good descriptions. Don't forget to comment code as well ! 

P.S: just realised this conflicts with your window.loop PR

**Comment by chancity** [comment]
looks good!

**Comment by ermiyaeskandary** [comment]
@ChadSki Rebase ... 

> This branch is out-of-date with the base branch
> Merge the latest changes from master into this branch.

**Comment by ermiyaeskandary** [comment]
LGTM !

**Comment by ChadSki** [comment]
Alright, I'm ready to merge! Take a look at the finished product [here](https://github.com/ChadSki/Slither.io-bot/blob/organize-code/bot.user.js).

There are three modules: `canvas`, `bot`, and `userInterface`.

The only stuff outside the modules are `window.log`, `window.loop`, the init function, and a few getters.

**Comment by ermiyaeskandary** [comment]
So...

**Comment by ermiyaeskandary** [comment]
Gimme a minute..

**Comment by ChadSki** [comment]
We'll need to update the [wiki page](https://github.com/ErmiyaEskandary/Slither.io-bot/wiki/Code-style#syntax) that says we're storing all global variables on the window object.

**Comment by K00sKlust** [comment]
:+1:

**Comment by ermiyaeskandary** [comment]
:+1:

**Comment by ermiyaeskandary** [comment]
LGTM

**Comment by K00sKlust** [comment]
LGTM

**Comment by ermiyaeskandary** [comment]
LGTM

**Comment by K00sKlust** [comment]
LGTM

**Comment by chancity** [comment]
LGTM

**Comment by Seple** [comment]
:+1:

**Pull request merged**
