### PR TITLE
added collision detection and collision settings

### PR DESCRIPTION
**Pull request by chancity**
Here's the latest bot with collision detection added.  Also fix slack! lol

### CODE REVIEW

**Comment by ermiyaeskandary** [comment]
Great - will test now.
Slack is with @FliiFe - fix it @FliiFe

**Comment by chancity** [comment]
Do you have skype?

**Comment by ermiyaeskandary** [comment]
Perfect - works. 
The visual debugging just needs fixing.
I'll also make you a collaborator :)
Congrats !

**Comment by ermiyaeskandary** [comment]
Done. 
You're a collaborator now. 
Congrats again !

**Comment by ermiyaeskandary** [comment]
> Do you have Skype ?
> Could I ask why you are asking that?

**Comment by chancity** [comment]
so i can speak to whomever

my skype name is chancey.hawbaker

**Comment by K00sKlust** [comment]
Hi! Why did you add `requestAnimationFrame`? The game has already the window.oef which is being called every frame, so you are calling `window.loop` twice. :) Well written though!

**Comment by ermiyaeskandary** [comment]
@chancity Gitter ! https://gitter.im/ErmiyaEskandary/Slither.io-bot

**Pull request merged**
