### PR TITLE
Remove unnessesary var declarations.

### PR DESCRIPTION
**Pull request by clemens-tolboom**
## Description

The variables used are only for storing the object which is immediately returned.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by ermiyaeskandary** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/250/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by Seple** [comment]
LGTM

**Comment by ChadSki** [comment]
:+1: Thanks for the cleanup work, much appreciated.

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/250/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by clemens-tolboom** [comment]
I do no see commit credits. Did I miss something?

**Comment by tjorim** [comment]
@clemens-tolboom When viewing the commits I can see your name: https://github.com/ErmiyaEskandary/Slither.io-bot/commits/master

**Comment by clemens-tolboom** [comment]
Thanks ... but it looks weird.

I'd overseen the second (earlier) commit. I wasn't aware this merge behavior.

commits_ _ermiyaeskandary_slither_io-bot

**Comment by tjorim** [comment]
Yeah I agree it's weird. + It makes the commit history cluttered as well.

**Comment by ChadSki** [comment]
Your commits were three separate PRs which ended up needing to be merged to create a linear history.

It makes more sense in the Network graph:

network graph

Although it would be more traditional if @ErmiyaEskandary prefixed those commits with a string like "Merge PR #250".

**Comment by tjorim** [comment]
@ChadSki Ah, I get it. So would creating a new branch on upstream make this look better?

Not only that, but I think changes should always be pushed to a branch on mainstream.
I think that others could edit that branch then as well (like Hound-complaints), isn't it?

**Comment by ermiyaeskandary** [comment]
We were talking about a default second branch being pushed.... The merge PR thing is in the commit message but I'll do it in the title next time...

**Comment by clemens-tolboom** [comment]
I'll check other projects I contributed to for similar behaviour. Thanks for the discussion :-)

Each PR can be pulled by others https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by ermiyaeskandary** [comment]
@clemens-tolboom The latest PR merge shows expected behaviour... :+1:

**Pull request merged**
