### PR TITLE
Grid system

### PR DESCRIPTION
**Pull request by j-c-m**
image

### CODE REVIEW

**Comment by joetex** [comment]
The area surrounding our bot is aligned into a GridSystem and weighted based on if there is Snake,Food, or Empty space.  This allows us to do LineTests, Cell Tests, and A\* Pathfinding on our grid.  These features will provide more tools to become a better bot.

## Description

Grid System with A\* pathfinding

## Motivation and Context

The bot must evolve!

## Screenshots (if appropriate):

## Types of changes


- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:




- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

**Comment by ermiyaeskandary** [comment]
Approved 

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/181/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by ermiyaeskandary** [comment]
I love net commits ! @ChadSki

**Comment by ChadSki** [comment]
Oh geez, we're now at 2670 lines? @_@

**Comment by ermiyaeskandary** [comment]
@ChadSki We were trying it just get it into master - cleaning up...

**Pull request merged**
