### PR TITLE
Make doc of snakes variable more precise.

### PR DESCRIPTION
**Pull request by clemens-tolboom**
## Description

The `window.snakes` variable does not contain **all** snakes. So it is not possible to base a strategy on it like find the biggest snake to attack.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by tjorim** [comment]
:+1: LGTM but not sure if we may merge, I think there was an agreement that only @FliiFe would alter the docs.

**Comment by ermiyaeskandary** [comment]
:+1: but ^^^^ @FliiFe ?

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/254/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by ChadSki** [comment]
:+1: LGTM but let's wait for @FliiFe 

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/254/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by tjbcg** [comment]
Currently, only the `docs` branch is used for docs. If you make a new PR (or you somehow manage to edit this one) to be merged into `docs` instead of `master`, then I'll approve that !

**Comment by tjbcg** [comment]
Oh, also, I can do the change for you if you don't want to bother remaking a PR, but it would be preferable for you to make it (in order for your name to appear in commit history, and in contributors)

**Comment by Drflash55** [comment]
So... What do you think, @FliiFe?

**Comment by tjbcg** [comment]
@Drflash55 Think about what ? 
About this PR, I'm 100% for the change.
About the one that should make those changes, I think it's better for @clemens-tolboom to remake a PR in order for him to appear in de contributors page, but I just wanted to tell him If he wants, I can do it.

**Comment by clemens-tolboom** [comment]
In https://github.com/ErmiyaEskandary/Slither.io-bot/issues/248#issuecomment-222599766 

> What bothers me about documentation is why is it in another branch. That doesn't make sense to me. It should be in the branch the developers / contributors work in. Unless it's a github pages website of course :-)

I just checked https://github.com/ErmiyaEskandary/Slither.io-bot/tree/docs which made me puzzled more. It does not seem like a special branch. If it is why? We all need the docs to be same up to date rate as the code right?

Please delete the docs branch in favour of master so we all are on the same page.

:-)

(my 2 cents)

**Comment by ChadSki** [comment]
Yeah the up-to-date documentation really should be in the master branch, so it lives with the code it describes.

**Comment by clemens-tolboom** [comment]
I forgot to add the docs would be in a readable online format.
- Not sure why table on https://github.com/ErmiyaEskandary/Slither.io-bot/blob/master/docs/game-variables.rst breaks.

Stupid I forgot https://github.com/ErmiyaEskandary/Slither.io-bot/blob/master/docs/conversion_algorithms.rst exists which explains map (doh)

**Comment by Defimatt** [comment]
:+1: I feel that if docs are in the same branch as the code itself, contributors and PR-submitters would be more likely to update the docs at the same time, because they'd be staring them in the face as they worked :stuck_out_tongue: 

Also added comment to #262

**Comment by tjbcg** [comment]
@clemens-tolboom Docs should not be read directly from github. They are located [here](http://slitherio-bot.readthedocs.io/en/latest/)

**Comment by clemens-tolboom** [comment]
@FliiFe thanks for the link

@all thanks for the support  :)

**Comment by ChadSki** [comment]
Oh I see, it's a readthedocs branch.

**Pull request merged**
