### PR TITLE
Detect FPS and set mobile rendering

### PR DESCRIPTION
**Pull request by GibsonHF**
Not tested yet but rough base

### CODE REVIEW

**Comment by ermiyaeskandary** [comment]
Conflicts - create a new fork and recommit.

**Comment by ermiyaeskandary** [comment]
Wouldn't work anyway I think ....

**Comment by GibsonHF** [comment]
oh alright, sorry was testing earlier but i'll fork again and try it. havent tested it either because i dont drop below 50 so was hoping someone would be able to

**Comment by ermiyaeskandary** [comment]
@FliiFe This should work ?

```
// Letter 'O' to change rendermode (visual)
        if (e.keyCode === 79) {
            window.mobileRender = !window.mobileRender;
            console.log('Mobile rendering set to: ' + window.mobileRender);
            window.savePreference('mobileRender', window.mobileRender);
           // toggles mobile render automatically based on FPS
            window.mobileRender = (window.framesPerSecond.getFPS() <= 20);
           // Set render mode
            if (window.mobileRender) {
                setBackground('data:image/gif;base64,R0lGODlhAQABAIAAAAUEBAAAACwAAAAAAQABAAACAkQBADs');
                window.render_mode = 1;
            } else {
                setBackground();
                window.render_mode = 2;
            }
        }

```

**Comment by Seple** [comment]
Similar problem #40

**Comment by ermiyaeskandary** [comment]
Rejected - we don't need this specific feature. Maybe check fps and decrease bot interval and vice versa ?

[Rejected with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/76/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Pull request closed without merging**
