### PR TITLE
Added quick radius toggle

### PR DESCRIPTION
**Pull request by Defimatt**
## Description

Added the ability to toggle the radius between two values with one key. Key description added to the overlay. Added properties to window.bot.opt to allow users to set their own values.
## Motivation and Context

When actively monitoring a session played by the bot, I often like to switch between two modes, which I call 'approach' and 'avoid'. In approach mode, I want the bot to get close to other snakes / food, and often use this mode when the snake is small (and I don't care about losing it) or there is high value food that is worth risking it for. In avoid mode, I want to stay as far away as possible from other snakes, even if that means losing out on food.

At the moment, I have to press / hold down A/S to alternate between these modes. (For example, I use a radius of 5 for approach and 25 for avoid; it takes a few keypresses or seconds of holding the key down to get from one to the other, in which time another snake could've killed me if I got too close while still having a small radius.)

This PR adds the ability to switch instantly between these two modes using the D key. If your current radius is exactly the approach or avoid radius, it switches to the opposite. If the radius is something else, it switches to the furthest one from your current radius.

Properties have been added to window.bot.opt to enable the user to choose their own avoid / approach values; these are: radiusApproachSz and radiusAvoidSz.

The overlay has been augmented to detail the functionality, with a reminder of the approach and avoid values chosen in bot.opt.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

User interface and logic changes to enable quick radius toggling.

### CODE REVIEW

**Comment by ermiyaeskandary** [comment]
@MattDuffin Great! Looks fantastic to me!
Approved!

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/237/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by ChadSki** [comment]
:+1: Nice work

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/237/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by Salvationdk** [comment]
i was looking for something like this... GJ

**Comment by Drflash55** [comment]
Approved. This seems like a really good tool to use...

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/237/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by Defimatt** [comment]
@Seple, I'm not quite sure what you mean. Could you explain again?

**Comment by Seple** [comment]
@MattDuffin Approach wheel 5 is too small and dangerous --->>> the lack of fast (comeback) return to normal setings

**Comment by Defimatt** [comment]
@Seple, `radiusApproachSize` and `radiusAvoidSize` are configurable in `window.bot.opt` to be your preferred radii.

**Pull request merged**
