### PR TITLE
Use the pythagorean theorem to find distance

### PR DESCRIPTION
**Pull request by Evanito**
a^2 + b^2 = c^2
Using two distances to calculate the magnitude of the vector

### CODE REVIEW

**Comment by tjbcg** [comment]
Why would you want to use the pythagorean theorem ? We don't need the real distance. Using squares is way more cpu expensive than not using squares.

**Comment by tjbcg** [comment]
We absolutely need to revert this. I'm sorry, no offence, but this is sooo computer expensive ! We didn't use pythagorean theorem on purpose.

**Comment by Drflash55** [comment]
So, it's now reverted... I would've liked for it to stay, and you coulda just optimized it, but @ErmiyaEskandary believes that it may not be possible.

**Comment by tjbcg** [comment]
@Drflash55 This _cannot_ be optimized. Squares and Squareroots are the most expensive task for a cpu. The optimized version is the one currently in the repo.

**Comment by Drflash55** [comment]
Mmm... Didn't know Exponents could be so hard on a CPU.

**Comment by tjbcg** [comment]
@Drflash55 Exponents, not _that_ much, but squareroots are litterally the most expensive task for a cpu.

**Comment by Drflash55** [comment]
@FliiFe Isn't it just the simple task of doing the reverse of squaring?

**Comment by tjbcg** [comment]
@Drflash55 Ewww. Simple task ? Mathematically, it sounds simple, but it takes between 50-100 cpu cycles. And it's about 13 times slower than an addition

**Comment by Drflash55** [comment]
@FliiFe Hmm... Makes sense...

**Pull request merged**
