### PR TITLE
No more doc branch 

### PR DESCRIPTION
**Pull request by ermiyaeskandary**
As discussed in #254, it seems like we shouldn't have a doc branch any more .... 

Approve or reject :+1: :-1:

### CODE REVIEW

**Comment by Defimatt** [comment]
:+1: I feel that if docs are in the same branch as the code itself, contributors and PR-submitters would be more likely to update the docs at the same time, because they'd be staring them in the face as they worked :stuck_out_tongue: 

Also added comment to #254

**Comment by tjorim** [comment]
:+1: Approve, this will make it a lot simpler.

**Comment by ermiyaeskandary** [comment]
:+1: Approved, obviously ;) 

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/262/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Comment by tjbcg** [comment]
Approved too.

[Approved with PullApprove](https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/pull-request/262/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=ErmiyaEskandary/Slither.io-bot)

**Pull request merged**
